### ISSUE TITLE
Offer lock/unlock command for all actuator devices

### ISSUE THREAD

**Issue by pfeifix** [brutella/hkknx-public#152]
The lock/unlock command (and related status) would make sense for all actuator devices. Currently the hkknx GUI only allows for configuring it for shutters, garage doors and fans. I need it at least for lamps and power outlets to prevent them from being controlled by local physical switches. My KNX actuators offer communication objects for these purposes.

_Originally posted by @pfeifix in https://github.com/brutella/hkknx-public/issues/135#issuecomment-992763685_

**Comment by brutella** [comment]
Blocking is currently only offered for the following types

- Occupancy Sensor
- Motion Sensor
- Contact Sensor
- Blind
- Garage Door
- Fan

This feature is not available for other accessories because of the reason how they would appear in the Apple Home app.
If blocking is enabled for an accessory, an additional switch is added to the accessory to block and unblock it. The Apple Home app includes the state of that switch in the description text as described in [this article](https://hochgatterer.me/de/hkknx/docs/accessories/block/) (German only).

For example a light bulb would appear as follow

1. The light is off and not blocked
![IMG_0F973D1A865B-1](https://user-images.githubusercontent.com/125641/146038582-e4acfbdb-9de1-407f-9c75-f2fdd5eadb8c.jpeg)

2. The light is off and blocked
![IMG_A6F8E7FA99FF-1](https://user-images.githubusercontent.com/125641/146038680-a5e501b6-4f24-4338-8c03-3f89c3e30d14.jpeg)

3. The light is on and blocked
![IMG_74CDF1BDABE6-1](https://user-images.githubusercontent.com/125641/146038942-f4048e0f-8ba5-44fe-903a-dcde7522e5f1.jpeg)

4. The light is on and not blocked
![IMG_E28A1D1AADAF-1](https://user-images.githubusercontent.com/125641/146038955-e0584450-b4b2-4098-b27e-a98ff51d55c9.jpeg)

That's just too confusing in my opinion. If you really need that feature, just create a switch named after the accessory which controls the blocked/unblocked status.

By the way – this is how it would look in the detail screen, which looks fine to me.
![IMG_C17C3DA41B2B-1](https://user-images.githubusercontent.com/125641/146039050-314cb450-bf0b-4fc9-af36-d2c6578922c1.jpeg)

**Comment by pfeifix** [comment]
Seems reasonable to me not to offer the blocked/unblocked feature as long as Apple decides to display it in this confusing manner. I have seen that my fan is displayed just as you described using the example of the lamp. Very disappointing. I hope Apple will figure out another (better) way to display the blocked/unblocked states for devices in the Home App.
