### ISSUE TITLE
Support DPT 251.600 for light color

### ISSUE THREAD

**Issue by brutella** [brutella/hkknx-public#35]

**Comment by brutella** [comment]
HomeKit expect light colours as HSB (Hue, Saturation, Brightness). On the other hand 251.600 expects the colour as RGBW. A conversion from HSB to RGBW seems doable but I couldn't find an algorithm to go from RGBW to HSB.

Therefore this feature is on hold for now.

**Comment by nico-rogasch** [comment]
I‘m trying to make my rgbw strip with lunatone dali 4ch controller in dim&color mode & MDT dali gateway work right now and and kinda got stuck on it.
I guess it‘s because of this unsupported datatype, but haven’t tried all combinations yet.
But i found this post on stackoverflow, do you know it already?
https://stackoverflow.com/questions/21117842/converting-an-rgbw-color-to-a-standard-rgb-hsb-representation

**Comment by nico-rogasch** [comment]
Googleing some more I found quiet a couple of articles about RGBW to HSB conversion, even a wikipedia entry : https://de.m.wikipedia.org/wiki/HSV-Farbraum
But I guess you already found them, so if this doesn’t work, could you eleborate the problems you encountered a bit more?

**Comment by bernd70** [comment]
Any updates here? I also would really like to have 251.600 support!

**Comment by brutella** [comment]
Fixed in [2.2.0](https://github.com/brutella/hkknx-public/releases/tag/2.2.0)
