### ISSUE TITLE
Support push buttons

### ISSUE THREAD

**Issue by brutella** [brutella/hkknx-public#40]
A push button (stateless programmable switch) should listen to group addresses and translate them to single, double and long press event.

**Comment by petnau** [comment]
Would this be a “HomeKit button” that you can use to trigger a specific KNX scene?

**Comment by brutella** [comment]
No, the other way round. A HomeKit button whose button presses (single, double, long press) are triggered by scenes. Those button presses can be used to trigger other actions, ex. turning on non-KNX HomeKit accessories.

**Comment by petnau** [comment]
With the existing options in the application today, is it possible to trigger KNX scenes?

**Comment by brutella** [comment]
No. If you want to see this feature, please open a new issue.

**Comment by BugRoger** [comment]
Imagine a GA that turns all lights ON/OFF. I would like to have a button that always sends an OFF to this GA.

Using the normal switch accessory doesn't work since it remembers state. I tried to initialise/read from a GA that is always ON. The switch accessory is smarter though and turns itself off anyway. In effect the switch needs to be pressed twice until it sends OFF again. Better than nothing but can't be used in scenes properly.

Not sure this feature will do that. A stateless programmable switch that always sends ON/OFF would be really nice to have though. 😄

**Comment by willgf** [comment]
Is there any update on this? Implementing it like Thinka has done it would be great: https://www.thinka.eu/faq/how-do-i-configure-my-push-button

**Comment by brutella** [comment]
@willgf So you want to have a button which is triggered by a group address? The button is then used to trigger actions in HomeKit?

**Comment by willgf** [comment]
Yes exactly. So the KNX pushbutton sends a scene number onto a group address, the bridge listens for this scene no on that GA. This means that can use your KNX "taster"/pushbuttons as triggers within Homekit. Ideally, with a single/long/double press. I really like the way Thinka implemented it (see their FAQ). 

Basically this would allow all scenes to "live" in HomeKit (which would also improve the user experience, as scenes can easily be changed within Homekit without ETS) with the KNX button merely acting as a trigger.

**Comment by brutella** [comment]
Push buttons are now available in pre-release [2.2.1](https://github.com/brutella/hkknx-public/releases/tag/2.2.1).

**Comment by willgf** [comment]
Yes, I think 8 (i.e. 4 rockers/Wippen). Thanks!
